### PR TITLE
draft: fix(server:handle-native-request): server handlers are not closing HttpConn after iterating over list of requests

### PR DESCRIPTION
**Pull request by pandres95**
Due to how the connections are handled (sometimes without even sending a response, but instead returning to keep on to the next request), and in part due to the nature of how Deno handles the requests, the `HttpConn` resource is not properly handled to close itself after async iteration finishes. This causes to Deno tests to raise a leaking ops error, like the following:

```bash

/orders => https://deno.land/std@0.148.0/testing/_test_suite.ts:191:10
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to accept a HTTP request was started in this test, but never completed. This is often caused by not closing a `Deno.HttpConn`. The operation was started here:
    at Object.opAsync (deno:core/01_core.js:157:42)
    at HttpConn.nextRequest (deno:ext/http/01_http.js:88:34)
    at Object.next (deno:ext/http/01_http.js:164:41)
    at handleLiteServer (https://raw.githubusercontent.com/alosaur/alosaur/master/src/server/handle-native-request.ts:227:20)

    at assert (deno:ext/web/00_infra.js:294:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:228:13)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:375:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:432:9)
    at async runTest (deno:runtime/js/40_testing.js:822:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:1111:22)
```

This PR attempts to fix this issue, by exposing a method `closeLeakedResources` that allows closing resources (`HttpConn`'s and server `Conn`s as well), whenever needed after a test finishes.

This is so the server can be run without needing to handle a forked application (when sometimes we need to get the logging of such fork).

### CODE REVIEW

**Comment by S0c5** [comment]
What is the status of this PR? someone could review this?

**Comment by irustm** [comment]
I think need run `deno fmt` for this PR

**Comment by pandres95** [comment]
Hey @irustm! Yup. It's a weird issue, because I've run it locally to fix the files several times. But even though you can see in the codebase that the file that's failing the check is indeed fine, `deno fmt` is still failing on CI. I'm investigating how to solve that, because this fix would be a great solution overall. 😊

**Comment by pandres95** [comment]
Gotcha! My `deno fmt --check` failed when a line didn't have a final semicolon. But CI's check failed on the presence of it. The main difference is the Deno version. I was using `1.27.1`, an the CI uses `1.20.3`.

My recommendation here would be updating checks until the latest version (`1.27.1`).

Note: This would also raise a lot of format errors related to typing.

**Pull request closed without merging**
