### PR TITLE
Add Chinese README file

### PR DESCRIPTION
**Pull request by borisliu**

### CODE REVIEW

**Comment by irustm** [comment]
Wow! thanks! 

please run `deno fmt` for format md file

**Comment by borisliu** [comment]
Done

**Comment by irustm** [comment]
hmm
```
from /home/runner/work/alosaur/alosaur/README_zh.md:
504 | -  }// 这个钩子在控制器操作之后执行
504 | +  } // 这个钩子在控制器操作之后执行
508 | -  }// 这个钩子当控制器操作抛出异常的时候执行
508 | +  } // 这个钩子当控制器操作抛出异常的时候执行

error: Found 1 not formatted file in 289 files
Error: Process completed with exit code 1.

```

**Comment by borisliu** [comment]
deno 1.7.0 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3

**Comment by irustm** [comment]
LGTM, thanks!

**Pull request merged**
